# Generated by Django 3.1.6 on 2021-03-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='exam_network.Course'),
        ),
    ]
