# Generated by Django 3.1.6 on 2021-03-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0003_result_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to='exam_network.User'),
        ),
    ]
