# Generated by Django 3.1.6 on 2021-03-20 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0006_auto_20210320_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='users',
            new_name='students',
        ),
    ]
