# Generated by Django 3.1.6 on 2021-03-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0008_auto_20210320_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='title',
            field=models.CharField(default='blank', max_length=50),
            preserve_default=False,
        ),
    ]
