# Generated by Django 3.1.6 on 2021-03-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0009_exam_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='exam',
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(to='exam_network.Question'),
        ),
    ]
