# Generated by Django 3.1.6 on 2021-03-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0013_auto_20210323_1506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='choice1',
            new_name='choice_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice2',
            new_name='choice_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice3',
            new_name='choice_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice4',
            new_name='choice_4',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choice5',
            new_name='choice_5',
        ),
    ]
