# Generated by Django 3.1.6 on 2021-03-23 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0014_auto_20210323_1506'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='Submission',
        ),
    ]
