# Generated by Django 3.0.7 on 2021-04-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0017_auto_20210403_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default='44ab1eb8d82d4c989829a1c52671d9d1', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default='935130b1e0e7498b86953ae9338b5931', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.UUIDField(default='66eb2aaa0fda40d68ad1eeedee918dbd', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default='417eaf11e45b481393179892b9b50a2a', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default='d0f08b6626df4793a8b4c1c70db5d455', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default='1a95452f88b84d7b846e04adcc6ec2e0', editable=False, primary_key=True, serialize=False),
        ),
    ]
