# Generated by Django 3.0.7 on 2021-04-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0018_auto_20210403_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default='8a0cadbd13a44a16a124b24a932788f8', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default='8a4b74dd186340568a1f9f72c9054fc8', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.UUIDField(default='83b61eb653d349f1b4b31d1c82beabf6', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default='dac113eaf59940159dd3ad68f35f3f25', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default='10d8fab768cd484db742961acc2c6290', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default='a2c8be4f9dc54835824cb40eec9c3895', editable=False, primary_key=True, serialize=False),
        ),
    ]
