# Generated by Django 3.0.7 on 2021-04-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0023_auto_20210404_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.UUIDField(default='52e9c33d41364a04bc8578e0955c2fa5', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.UUIDField(default='f97116131ee6439fa81813111622ff9b', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='id',
            field=models.UUIDField(default='b5c3cfe9454f42189f78f107da5645f8', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default='7451a42af00f46cc836bc9d32ac3bc23', editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='id',
            field=models.UUIDField(default='30a8987f8f8f49d5bc64b9bd0cf60c69', editable=False, primary_key=True, serialize=False),
        ),
    ]
