# Generated by Django 3.1.6 on 2021-04-04 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0025_auto_20210404_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('S', 'Student'), ('T', 'Teacher'), ('N', 'None')], default='N', max_length=1),
        ),
    ]
