# Generated by Django 3.0.7 on 2021-04-05 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_network', '0026_auto_20210404_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='percentage',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
